export const ar = {
    menuItems: 'النشاطات المحاسبية',
    rptItems: 'التقارير',
    copyright: 'جميع الحقوق محفوظة لشركة ',
    costCenterTitle: 'مراكز التكلفة',
    centerNameError: 'بالرجاء اضافة اسم المركز',
    centerCodeError: 'بالرجاء اضافة كود المركز',
    final: 'Final',
    loadingSerachOptions: 'جار تحميل البيانات ...',
    SerachByOptions: "ابحث ب",
    SearchOperator: "اختر العلامة",
    searchValue: "القيمة",
    searchButton: "بحث",
    taskBarNew: 'جديد',
    taskBarSave: 'حفظ',
    taskBarPrint: "طباعة",
    taskBarDelete: "حذف",
    taskBarView: "عرض",
    taskBarRefresh: "اعادة تعيين",
    delete: "حذف",
    cancel: "الغاء",
    deleteConfirmTitle: "هل تود حذف هذا السجل؟ نعم, لا", 
    chooseRep: 'اختر التقرير',
    repPrint: "طباعة",
    repDisplay: "عرض",
    deleteMsgTitle: "حذف البيانات",
    deleteMsgDetails: "تمت عملية الحذف بنجاح",
    editMsgTitle: "تعديل البيانت",
    editMsgDetails: "تمت عملية التعديل بنجاح",
    addMsgTitle: "اضافة سجل",
    addMsgDetails: "تمت اضافة سجل جديد بنجاح",
    warningMsgTitle: "لا يمكن اتمام العملية",
    warningMsgDetails: "بالرجاء ملئ جميع البيانات المطلوبة",
    defaultFormtitle: "اضافة سجل",
    editFormTitle: "تعديل السجل"     
}

export const en = {
    menuItems: 'Acounting Activites',
    rptItems: 'Reports',
    copyright: 'All Rights Reserved by ',
    centerNameError: 'Center name is required',
    centerCodeError: 'Center code is required',
    final: 'Final',
    loadingSerachOptions: 'Loading data ...',
    SerachByOptions: "Search by",
    SearchOperator: "Select operator",
    searchValue: "Value",
    searchButton: "Search",
    taskBarNew: 'New',
    taskBarSave: 'Save',
    taskBarPrint: "Print",
    taskBarDelete: "Delete",
    taskBarView: "View",
    taskBarRefresh: "Reset",  
    delete: "Delete",
    cancel: "Cancel",
    deleteConfirmTitle: "Do you want to delete this record? Yes, No",
    chooseRep: 'Choose Report',
    repPrint: "Print",
    repDisplay: "Display",
    deleteMsgTitle: "Delete Data",
    deleteMsgDetails: "Data deleted successfully",
    editMsgTitle: "Edit Data",    
    editMsgDetails: "Data edited successfully",
    addMsgTitle: "Add Record",
    addMsgDetails: "New record added successfully",
    warningMsgTitle: "Cannot Complete Your Action",
    warningMsgDetails: "Please complete all required fields",
    defaultFormtitle: "New Record",
    editFormTitle: "Edit Record" 
}

export const lang = localStorage.getItem("dictionary");