export const ar = {
    menuItems: 'النشاطات المحاسبية',
    rptItems: 'التقارير',
    copyright: 'جميع الحقوق محفوظة لشركة ',
    costCenterTitle: 'مراكز التكلفة',
    centerNameError: 'بالرجاء اضافة اسم المركز',
    centerCodeError: 'بالرجاء اضافة كود المركز',
    final: 'Final',
    loadingSerachOptions: 'جار تحميل البيانات ...',
    SerachByOptions: "ابحث ب",
    SearchOperator: "اختر العلامة",
    searchValue: "القيمة",
    searchButton: "بحث",
    taskBarNew: 'جديد',
    taskBarSave: 'حفظ',
    taskBarPrint: "طباعة",
    taskBarDelete: "حذف",
    taskBarView: "عرض",
    taskBarRefresh: "اعادة تعيين",
    delete: "نعم",
    cancel: "لا",
    deleteConfirmTitle: "هل تود حذف هذا السجل؟", 
    chooseRep: 'اختر التقرير',
    repPrint: "طباعة",
    repDisplay: "عرض",
    deleteMsgTitle: "حذف البيانات",
    deleteMsgDetails: "تمت عملية الحذف بنجاح",
    editMsgTitle: "تعديل البيانت",
    editMsgDetails: "تمت عملية التعديل بنجاح",
    addMsgTitle: "اضافة سجل",
    addMsgDetails: "تمت اضافة سجل جديد بنجاح",
    warningMsgTitle: "لا يمكن اتمام العملية",
    warningMsgDetails: "بالرجاء ملئ جميع البيانات المطلوبة",
    deleteTransTypeMsgDetails: "غير مسموح للنظام بحذف هذا السجل",
    defaultFormtitle: "اضافة سجل",
    editFormTitle: "تعديل السجل",
    noReports: "لا توجد تقارير متاحة",
    creditForCustomer: "أيام (مدة العميل)",
    creditForSalesmen: "أيام (مدة البائع)",   
    validValueMsgTitle: "بيانات غير موجودة",
    validValueMsgDetails: "البيانات التي ادخلتها غير موجودة بالرجاء ادخالة قيمة موجودة",
    canNotDeleteMsgDetails: "لا يمكن حذف هذا السجل لانه مستخدم في جداول اخرى",
    approveWarningMsgTitle: "عملية الموافقة",
    approveWarningMsgDetails: "لا يمكنك الموافقة على معاملات الفروع الأخرى",
    approveConfirmTitle: "هل انت متأكد؟",
    approveConfirmMsg: "لا يمكن الغاء العملية بعد اتمامها!!",
    approveTitle: "تأكيد العملية",
    approveSuccess: "تمت عملية التأكيد بنجاح",
    approveFail: "فشلت عملية التأكيد بالرجاء المحاولة لاحقا",
    cancelWarningMsgDetails: "لا يمكن الغاء العملية بعد اتمامها!!",
    cancelWarningMsgTitle: "الغاء العملية",
    closeDatePlaceHolder: "اختر تاريخ الاقفال",
    closeDateWarningTitle: "تاريخ الاغلاق",
    closeDateWarningMsg: "بالرجاء اختيار تاريخ الاغلاق",
    reportName: "اسم التقرير",
    reportValidationMsgTitle: "تحقق من التقرير",
    reportValidationMsgDetails: "لا يمكن للقيمة ان تكون فارغة بالرجاء اختيار قيمة",
    loginBtnText: "تسجيل الدخول",
    loginHeadText: "تسجيل الدخول الى MIS",
    authErrorMsgTitle: "تسجيل الدخول",
    authErrorMsgDetails: "اسم المستخدم و/او كلمة المرور غير صحيحة",
    authWelcomeMsg: "مرحبا",
    authWelcomeMsgDetails: "تمت عملية تسجيل الدخول بنجاح",
    genericErrMsgTitle: "حدث خطأ",
    genericErrMsgDetails: "لا يمكن إكمال الإجراء ، يرجى المحاولة مرة أخرى لاحقًا",
    authWarningMsgTitle: "تسجيل الدخول",
    authWarningMsgDetails: "يجب عليك تسجيل الدخول لادارة تطبيق MIS",
    signOutMsgTitle: "تسجيل الخروج",
    signOutMsgDetails: "تمت عملية تسجيل الخروج بنجاح",
    pwpCheckRequired: "بالرجاء تأكيد كلمة المرور",
    pwpCheckNotMatch: "كلمتا المرور غير متطابقتان",
    changePwpBtn: "تغير كلمة المرور",
    changePwpMsgTitle: "تغير كلمة المرور",
    changePwpMsgDetails: "تم تغير كلمة المرور بنجاح",
    changePwpMsgFail: "كلمة المرور السابقة غير صحيحة",
    btnUpdate: "تحديث",
    uploadLogo: "علامة تجارية جديدة",
    uploadSmLogo: "علامة تجارية مصغرة جديدة",
    uploadWatermark: "علامة مائية جديدة",
    systemPreferencesMsgTitle: "اعدادات النظام",
    systemPreferencesMsgDetails: "تم تحديث اعدادات النظام بنجاح",
    postDate: "حتى تاريخ",
    emptyDateMsgTitle:"التاريخ",
    emptyDateMsgDetails: "بالرجاء اختيار التاريخ",
    postingMsgTitle: "الترحيل",
    postingMsgDetails: "تم الترحيل بنجاح ل",
    unpostingMsgTitle: "الغاء الترحيل",
    unpostingMsgDetails: "تم الغاء الترحيل بنجاح ل",
    noSelectedAccountMsgTitle: "لا يوجد حساب مختار",
    noSelectedAccountMsgDetails: "بالرجاء اختيار حساب لاكمال العملية",
    addUserEventMsgTitle: "الاحداث",
    addUserEventMsgMsg: "تمت اضافة المستخدم الى الحدث بنجاح",
    removeUserEventMsgTitle: "الاحداث",
    removeUserEventMsgMsg: "تمت ازالة المستخدم من الحدث بنجاح",
    customerRequestMsgTitle: "المجموعة",
    customerRequestMsgDetails: "بالرجاء اختيار المجموعة حتى تتمكن من اختيار المجموعة الفرعية",
    tradeMsgTitle: "الرخصة التجارية",
    tradeMsgDetails: "لا يمكن تكرار الرخصة التجارية",
    genericMailMsgTitle: "البريد الالكتروني",
    genericMailMsgDetails: "تم ارسال البريد الالكتروني بنجاح",
    genericMailMsgErrDetails: "حدث خطأ اثناء ارسال البريد الالكتروني",
    inActivePaymentTermMsgTitle: "طريقة الدفع غير مفعلة",
    inActivePaymentTermMsgDetails: "طريقة الدفع غير مفعلة , بالرجاء اختيار طريقة دفع اخرى",
    warningGenericMsgTitle: "معلومات مفقودة",
    noCustMsgDetails: "بالرجاء اختيار العميل",
    quantityMsgDetails: "ََلا يمكن للكمية ان تكون اقل من 0",
    missingItemCodeMsgDetails: "بالرجاء اختيار صنف",
    missingCustomerMsgDetails: "بالرجاء اختيار عميل",
    missingGridrMsgDetails: "بالرجاء اختيار صنف واحد على الاقل قبل عملية الحفظ",
    cannotEditInvoiced: "عنصر مفوتر",
    cannotEditInvoicedDetails: "لا يمكن التعديل او حذف هذا الصنف, تم اصدار فاتورة لهذا الصنف",
    changeInvoicConfirmTitle: "هل تود الاستمرار؟",
    confirm: "تأكيد",
    cannotEditQuantity: "تعديل الكمية",
    cannotEditQuantityDetails: "لا يمكن للكمية ان تكون اقل من عدد الفواتير لهذا الصنف",
    cancelledMsgDetails: "لا يمكن للكمية الملغاة ان تكون اقل من 0",
    warningInValidDateTitle: "التاريخ",
    inValidDateMsgDetails: "تاريخ التوصيل غير صالح",
    missingAmountDetails: "لا يمكن للمبلغ ان يوكن صفر",
    custMsgTitle: "كود العميل",
    custMsgDetails: "لا يمكن تغير كود العميل لهذا الطلب بسبب وجود فاتورة او اكثر",
    purOrderMsgTitle: "رقم شراء",
    purOrderMsgDetails: "لا يمكن تكرار رقم الشراء",
    creditForMsgTitle: "تاريخ الاستحقاق",
    creditForDetails: "ليس لديك صلاحية تعديل تاريخ الاستحقاق"
}

export const en = {
    menuItems: 'Acounting Activites',
    rptItems: 'Reports',
    copyright: 'All Rights Reserved by ',
    centerNameError: 'Center name is required',
    centerCodeError: 'Center code is required',
    final: 'Final',
    loadingSerachOptions: 'Loading data ...',
    SerachByOptions: "Search by",
    SearchOperator: "Select operator",
    searchValue: "Value",
    searchButton: "Search",
    taskBarNew: 'New',
    taskBarSave: 'Save',
    taskBarPrint: "Print",
    taskBarDelete: "Delete",
    taskBarView: "View",
    taskBarRefresh: "Reset",  
    delete: "Yes",
    cancel: "No",
    deleteConfirmTitle: "Do you want to delete this record?",
    chooseRep: 'Choose Report',
    repPrint: "Print",
    repDisplay: "Display",
    deleteMsgTitle: "Delete Data",
    deleteMsgDetails: "Data deleted successfully",
    editMsgTitle: "Edit Data",    
    editMsgDetails: "Data edited successfully",
    addMsgTitle: "Add Record",
    addMsgDetails: "New record added successfully",
    warningMsgTitle: "Cannot Complete Your Action",
    warningMsgDetails: "Please complete all required fields",
    deleteTransTypeMsgDetails: "System not allowed to delete this record",
    defaultFormtitle: "New Record",
    editFormTitle: "Edit Record",
    noReports: "No Available Reports",
    creditForCustomer: "Days(Customer Term)",
    creditForSalesmen: "Days(Salesman Term)",
    validValueMsgTitle: "No Value",
    validValueMsgDetails: "The value you entered is not exists, please enter existing value",
    canNotDeleteMsgDetails: "You Cannot delete this record because it used in other tables",
    approveWarningMsgTitle: "Approve Process",
    approveWarningMsgDetails: "You can't approve other branches transactions",
    approveConfirmTitle: "Are you Sure?",
    approveConfirmMsg: "If the transaction is posted you'll never be able to disapprove it again.",
    approveTitle: "Approve Transaction",
    approveSuccess: "Transaction approved successfully",
    approveFail: "Approved failed, please try again later",
    cancelWarningMsgDetails: "If the transaction is posted you'll never be able to disapprove it again.",
    cancelWarningMsgTitle: "Cancel Transaction",
    closeDatePlaceHolder: "Select close date",
    closeDateWarningTitle: "Close Date",
    closeDateWarningMsg: "Please select close date",
    reportName: "Report Name",
    reportValidationMsgTitle: "Report Validation",
    reportValidationMsgDetails: "Value cannot be empty, please select one",
    loginBtnText: "Sign In",
    loginHeadText: "Sign in to MIS",
    authErrorMsgTitle: "Singin",
    authErrorMsgDetails: "Invalid username and/or password",
    authWelcomeMsg: "Welcome",
    authWelcomeMsgDetails: "You signed in successfully",
    genericErrMsgTitle: "Something Wrong",
    genericErrMsgDetails: "Cannot complete the action, please try again later",
    authWarningMsgTitle: "Sing In",
    authWarningMsgDetails: "You have to sign in to access MIS app",
    signOutMsgTitle: "Sign Out",
    signOutMsgDetails: "You signed out successfully",
    pwpCheckRequired: "Please confirm your password!",
    pwpCheckNotMatch: "Two passwords that you enter is inconsistent!",
    changePwpBtn: "Change Password",
    changePwpMsgTitle: "Change Password",
    changePwpMsgDetails: "Password changed successfully",
    changePwpMsgFail: "Old password is invalid",
    btnUpdate: "Update",
    uploadLogo: "New Logo",
    uploadSmLogo: "New Small Logo",
    uploadWatermark: "Nwe Watermark",
    systemPreferencesMsgTitle: "System Preferences",
    systemPreferencesMsgDetails: "Preferences updated successfully",
    postDate: "Up to Date",
    emptyDateMsgTitle:"Empty Date",
    emptyDateMsgDetails: "Please choose a date",
    postingMsgTitle: "Posting",
    postingMsgDetails: "Posting succeed for",
    unpostingMsgTitle: "UnPosting",
    unpostingMsgDetails: "UnPosting succeed for",
    noSelectedAccountMsgTitle: "No Selected Account",
    noSelectedAccountMsgDetails: "Please select an account to complete the operation",
    addUserEventMsgTitle: "Add User to Event",
    addUserEventMsgMsg: "User/s added to the event successfully",
    removeUserEventMsgTitle: "Remove User from Event",
    removeUserEventMsgMsg: "User/s removed from the event successfully",
    customerRequestMsgTitle: "Group",
    customerRequestMsgDetails: "Please select group before selecting sub group",
    tradeMsgTitle: "Trade License",
    tradeMsgDetails: "Trade License Number can not be duplicated.",
    genericMailMsgTitle: "Email",
    genericMailMsgDetails: "Email sent successfully",
    genericMailMsgErrDetails: "something went wrong while sending the email",
    inActivePaymentTermMsgTitle: "Inactive Payment",
    inActivePaymentTermMsgDetails: "This is an inactive term, pls. choose another payment term",
    warningGenericMsgTitle: "Missing Information",
    noCustMsgDetails: "Please select customer first",
    quantityMsgDetails: "ََQuantity cannot be less than 0",
    missingItemCodeMsgDetails: "Please select an item",
    missingCustomerMsgDetails: "Please select customer",
    missingGridrMsgDetails: "Please select at least one item before saving",
    cannotEditInvoiced: "Invoiced Item",
    cannotEditInvoicedDetails: "You cannot modify or delete this item, total Qty is already invoiced!",
    changeInvoicConfirmTitle: "Do you want to continue?",
    confirm: "Confirm",
    cannotEditQuantity: "Modify Quantity",
    cannotEditQuantityDetails: "Quantity cannot be less than number of invoices",
    cancelledMsgDetails: "Cancelled quantity cannot be less than 0",
    warningInValidDateTitle: "Date",
    inValidDateMsgDetails: "Invalid delivery date",
    missingAmountDetails: "Amount cannot be zero",
    custMsgTitle: "Customer Code",
    custMsgDetails: "You can not change customer code because there is one or more invoice on this order",
    purOrderMsgTitle: "Purchase Order",
    purOrderMsgDetails: "Purchase Order cannot be duplicated.",
    creditForMsgTitle: "Due Date",
    creditForDetails: "You don't have the rights to increase the terms due date"
}

export const lang = localStorage.getItem("dictionary");